[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1", "with-chrono-0_4"] }
actix-web = "4"
serde = { version = "1.0.136", features = ["derive"] }
deadpool-postgres = { version = "0.10.2", features = ["serde"] }
config = "0.13.1"
derive_more = "0.99.17"
env_logger = "0.9.0"
log = "0.4.16"
serde_json = "1.0.79"
futures = "0.3.21"
uuid = { version = "0.8.2", features = ["v4"] }
actix-service = "2.0.2"
chrono = { version = "0.4.19", features = ["serde"] }
actix-cors = "0.6.1"
aes-gcm = "0.9.4"
rand = "0.8.5"
blake2 = "0.10.4"
data-encoding = { version = "2.3.2", features = ["alloc"] }
lazy_static = "1.4.0"
regex = "1.5.5"